---
abstract: 'run test scripts via browser'
author:
  - 'Renee Baecker <module@renee-baecker.de>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-Prove
requires:
  App::Prove: 0
  Capture::Tiny: 0
  Cwd: 0
  File::Basename: 0
  File::Find::Rule: 0
  File::Spec: 0
  Mojolicious: 3.51
version: 0.01
